apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mysql-svc
spec:
  type: ClusterIP
  selector:
      app.kubernetes.io/name: {{ .Release.Name }}-mysql
  ports:
    - name: mysql
      port: {{ .Values.mysql.service.port }}
      targetPort: mysql
