doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '16'

        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true
        types:
            user_id: App\User\Infrastructure\Doctrine\Type\UserIdType
            email: App\User\Infrastructure\Doctrine\Type\EmailType
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        identity_generation_preferences:
            Doctrine\DBAL\Platforms\PostgreSQLPlatform: identity
        auto_mapping: true
        mappings:
            Order:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Order/Domain'
                prefix: 'App\Order\Domain'
                alias: Order
            Payment:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Payment/Domain'
                prefix: 'App\Payment\Domain'
                alias: Payment
            User:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/User/Domain'
                prefix: 'App\User\Domain'
                alias: User
            Wallet:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Wallet/Domain'
                prefix: 'App\Wallet\Domain'
                alias: Wallet
            SharedOutbox:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Shared/Infrastructure/Outbox/Doctrine'
                prefix: 'App\Shared\Infrastructure\Outbox\Doctrine'
                alias: SharedOutbox
        controller_resolver:
            auto_mapping: false

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
